#ifndef PORTAL_LITE_CONSTANTS_H
#define PORTAL_LITE_CONSTANTS_H

#define BUTTON_THRESHOLD_LONG 500

#define PIN_BUTTON_LEFT 34
#define PIN_BUTTON_RIGHT 35
#define PIN_BUZZER 4

#define WRITE_MIN_DELAY 1000

#define BEEP_SHORT 100
#define BEEP_LONG 1000


#endif //PORTAL_LITE_CONSTANTS_H
